import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

//run npx prisma db seed
//https://docs.google.com/spreadsheets/d/1v6H1J9vwVyJ6uML0pvl0mAJ75tWW412GwNt8w1Ymhn0/edit?usp=sharing

async function main() {

  const onansAnteChamber = await prisma.flo.create({
    data: {
      author: "chitters",
      name: "Debut",
      level: 'LIGHT',
      cost: 0,
      chits: {
        create: [
          { name: "BABYDRIVER", link: "https://chits-video.s3.amazonaws.com/chitters_debut_BABYDRIVER.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_BABYDRIVER.png", level: "LIGHT" },
          { name: "BACK", link: "https://chits-video.s3.amazonaws.com/chitters_debut_BACK.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_BACK.png", level: "LIGHT" },
          { name: "BASEBALLBIRD", link: "https://chits-video.s3.amazonaws.com/chitters_debut_BASEBALLBIRD.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_BASEBALLBIRD.png", level: "LIGHT" },
          { name: "BASICINSTINCT", link: "https://chits-video.s3.amazonaws.com/chitters_debut_BASICINSTINCT.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_BASICINSTINCT.png", level: "LIGHT" },
          { name: "BKFSTCLUB", link: "https://chits-video.s3.amazonaws.com/chitters_debut_BKFSTCLUB.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_BKFSTCLUB.png", level: "LIGHT" },
          { name: "BOBROSS", link: "https://chits-video.s3.amazonaws.com/chitters_debut_BOBROSS.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_BOBROSS.png", level: "LIGHT" },
          { name: "BONITA", link: "https://chits-video.s3.amazonaws.com/chitters_debut_BONITA.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_BONITA.png", level: "LIGHT" },
          { name: "BRINGOUTDEAD", link: "https://chits-video.s3.amazonaws.com/chitters_debut_BRINGOUTDEAD.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_BRINGOUTDEAD.png", level: "LIGHT" },
          { name: "BUELLER", link: "https://chits-video.s3.amazonaws.com/chitters_debut_BUELLER.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_BUELLER.png", level: "LIGHT" },
          { name: "CRUISEONOPRAH", link: "https://chits-video.s3.amazonaws.com/chitters_debut_CRUISEONOPRAH.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_CRUISEONOPRAH.png", level: "LIGHT" },
          { name: "DADISGREAT", link: "https://chits-video.s3.amazonaws.com/chitters_debut_DADISGREAT.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_DADISGREAT.png", level: "LIGHT" },
          { name: "DAMELIO", link: "https://chits-video.s3.amazonaws.com/chitters_debut_DAMELIO.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_DAMELIO.png", level: "LIGHT" },
          { name: "DOFLIP", link: "https://chits-video.s3.amazonaws.com/chitters_debut_DOFLIP.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_DOFLIP.png", level: "LIGHT" },
          { name: "ESCALATED", link: "https://chits-video.s3.amazonaws.com/chitters_debut_ESCALATED.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_ESCALATED.png", level: "LIGHT" },
          { name: "EXIT12", link: "https://chits-video.s3.amazonaws.com/chitters_debut_EXIT12.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_EXIT12.png", level: "LIGHT" },
          { name: "FACEPALM", link: "https://chits-video.s3.amazonaws.com/chitters_debut_FACEPALM.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_FACEPALM.png", level: "LIGHT" },
          { name: "FAIRENOUGH", link: "https://chits-video.s3.amazonaws.com/chitters_debut_FAIRENOUGH.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_FAIRENOUGH.png", level: "LIGHT" },
          { name: "FF", link: "https://chits-video.s3.amazonaws.com/chitters_debut_FF.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_FF.png", level: "LIGHT" },
          { name: "FLEETWOOD", link: "https://chits-video.s3.amazonaws.com/chitters_debut_FLEETWOOD.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_FLEETWOOD.png", level: "LIGHT" },
          { name: "FLEXPASTE", link: "https://chits-video.s3.amazonaws.com/chitters_debut_FLEXPASTE.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_FLEXPASTE.png", level: "LIGHT" },
          { name: "FOXES", link: "https://chits-video.s3.amazonaws.com/chitters_debut_FOXES.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_FOXES.png", level: "LIGHT" },
          { name: "GLADIATOR", link: "https://chits-video.s3.amazonaws.com/chitters_debut_GLADIATOR.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_GLADIATOR.png", level: "LIGHT" },
          { name: "GREATSUCCESS", link: "https://chits-video.s3.amazonaws.com/chitters_debut_GREATSUCCESS.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_GREATSUCCESS.png", level: "LIGHT" },
          { name: "GROOT", link: "https://chits-video.s3.amazonaws.com/chitters_debut_GROOT.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_GROOT.png", level: "LIGHT" },
          { name: "HAND", link: "https://chits-video.s3.amazonaws.com/chitters_debut_HAND.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_HAND.png", level: "LIGHT" },
          { name: "HELLOTHERE", link: "https://chits-video.s3.amazonaws.com/chitters_debut_HELLOTHERE.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_HELLOTHERE.png", level: "LIGHT" },
          { name: "HOMERBUSHES", link: "https://chits-video.s3.amazonaws.com/chitters_debut_HOMERBUSHES.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_HOMERBUSHES.png", level: "LIGHT" },
          { name: "HOWBIZARRE", link: "https://chits-video.s3.amazonaws.com/chitters_debut_HOWBIZARRE.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_HOWBIZARRE.png", level: "LIGHT" },
          { name: "IFIDIDNTWIN", link: "https://chits-video.s3.amazonaws.com/chitters_debut_IFIDIDNTWIN.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_IFIDIDNTWIN.png", level: "LIGHT" },
          { name: "IHAVEDREAM", link: "https://chits-video.s3.amazonaws.com/chitters_debut_IHAVEDREAM.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_IHAVEDREAM.png", level: "LIGHT" },
          { name: "IMBATMAN", link: "https://chits-video.s3.amazonaws.com/chitters_debut_IMBATMAN.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_IMBATMAN.png", level: "LIGHT" },
          { name: "IMOBSSESSED", link: "https://chits-video.s3.amazonaws.com/chitters_debut_IMOBSSESSED.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_IMOBSSESSED.png", level: "LIGHT" },
          { name: "INTROHER", link: "https://chits-video.s3.amazonaws.com/chitters_debut_INTROHER.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_INTROHER.png", level: "LIGHT" },
          { name: "ITSOVER", link: "https://chits-video.s3.amazonaws.com/chitters_debut_ITSOVER.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_ITSOVER.png", level: "LIGHT" },
          { name: "ITSWEDNESDAY", link: "https://chits-video.s3.amazonaws.com/chitters_debut_ITSWEDNESDAY.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_ITSWEDNESDAY.png", level: "LIGHT" },
          { name: "JAMESON", link: "https://chits-video.s3.amazonaws.com/chitters_debut_JAMESON.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_JAMESON.png", level: "LIGHT" },
          { name: "JUSTABABY", link: "https://chits-video.s3.amazonaws.com/chitters_debut_JUSTABABY.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_JUSTABABY.png", level: "LIGHT" },
          { name: "KHABY", link: "https://chits-video.s3.amazonaws.com/chitters_debut_KHABY.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_KHABY.png", level: "LIGHT" },
          { name: "KIDONCRACK", link: "https://chits-video.s3.amazonaws.com/chitters_debut_KIDONCRACK.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_KIDONCRACK.png", level: "LIGHT" },
          { name: "KUNGFU", link: "https://chits-video.s3.amazonaws.com/chitters_debut_KUNGFU.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_KUNGFU.png", level: "LIGHT" },
          { name: "LETITDIE", link: "https://chits-video.s3.amazonaws.com/chitters_debut_LETITDIE.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_LETITDIE.png", level: "LIGHT" },
          { name: "LIGHTISDYING", link: "https://chits-video.s3.amazonaws.com/chitters_debut_LIGHTISDYING.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_LIGHTISDYING.png", level: "LIGHT" },
          { name: "LOGANROY", link: "https://chits-video.s3.amazonaws.com/chitters_debut_LOGANROY.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_LOGANROY.png", level: "LIGHT" },
          { name: "MCGREGOR", link: "https://chits-video.s3.amazonaws.com/chitters_debut_MCGREGOR.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_MCGREGOR.png", level: "LIGHT" },
          { name: "MELANIE", link: "https://chits-video.s3.amazonaws.com/chitters_debut_MELANIE.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_MELANIE.png", level: "LIGHT" },
          { name: "MILDBURN", link: "https://chits-video.s3.amazonaws.com/chitters_debut_MILDBURN.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_MILDBURN.png", level: "LIGHT" },
          { name: "MILEY", link: "https://chits-video.s3.amazonaws.com/chitters_debut_MILEY.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_MILEY.png", level: "LIGHT" },
          { name: "MIRRORGUY", link: "https://chits-video.s3.amazonaws.com/chitters_debut_MIRRORGUY.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_MIRRORGUY.png", level: "LIGHT" },
          { name: "MJPOPCORN", link: "https://chits-video.s3.amazonaws.com/chitters_debut_MJPOPCORN.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_MJPOPCORN.png", level: "LIGHT" },
          { name: "MONSTERS", link: "https://chits-video.s3.amazonaws.com/chitters_debut_MONSTERS.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_MONSTERS.png", level: "LIGHT" },
          { name: "MYBOY", link: "https://chits-video.s3.amazonaws.com/chitters_debut_MYBOY.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_MYBOY.png", level: "LIGHT" },
          { name: "NEEDFORSPEED", link: "https://chits-video.s3.amazonaws.com/chitters_debut_NEEDFORSPEED.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_NEEDFORSPEED.png", level: "LIGHT" },
          { name: "NOLIKESAND", link: "https://chits-video.s3.amazonaws.com/chitters_debut_NOLIKESAND.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_NOLIKESAND.png", level: "LIGHT" },
          { name: "NOTABTMONEY", link: "https://chits-video.s3.amazonaws.com/chitters_debut_NOTABTMONEY.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_NOTABTMONEY.png", level: "LIGHT" },
          { name: "NOTFUNNYOK", link: "https://chits-video.s3.amazonaws.com/chitters_debut_NOTFUNNYOK.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_NOTFUNNYOK.png", level: "LIGHT" },
          { name: "NYEBOWL", link: "https://chits-video.s3.amazonaws.com/chitters_debut_NYEBOWL.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_NYEBOWL.png", level: "LIGHT" },
          { name: "OBAMA", link: "https://chits-video.s3.amazonaws.com/chitters_debut_OBAMA.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_OBAMA.png", level: "LIGHT" },
          { name: "ONEJOB", link: "https://chits-video.s3.amazonaws.com/chitters_debut_ONEJOB.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_ONEJOB.png", level: "LIGHT" },
          { name: "PISTON", link: "https://chits-video.s3.amazonaws.com/chitters_debut_PISTON.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_PISTON.png", level: "LIGHT" },
          { name: "POARCH", link: "https://chits-video.s3.amazonaws.com/chitters_debut_POARCH.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_POARCH.png", level: "LIGHT" },
          { name: "POPE", link: "https://chits-video.s3.amazonaws.com/chitters_debut_POPE.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_POPE.png", level: "LIGHT" },
          { name: "REDDRESSGIRL", link: "https://chits-video.s3.amazonaws.com/chitters_debut_REDDRESSGIRL.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_REDDRESSGIRL.png", level: "LIGHT" },
          { name: "RICKROLL", link: "https://chits-video.s3.amazonaws.com/chitters_debut_RICKROLL.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_RICKROLL.png", level: "LIGHT" },
          { name: "ROCKY", link: "https://chits-video.s3.amazonaws.com/chitters_debut_ROCKY.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_ROCKY.png", level: "LIGHT" },
          { name: "SAYANYTHING", link: "https://chits-video.s3.amazonaws.com/chitters_debut_SAYANYTHING.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_SAYANYTHING.png", level: "LIGHT" },
          { name: "SHANIA", link: "https://chits-video.s3.amazonaws.com/chitters_debut_SHANIA.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_SHANIA.png", level: "LIGHT" },
          { name: "SOSORRY", link: "https://chits-video.s3.amazonaws.com/chitters_debut_SOSORRY.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_SOSORRY.png", level: "LIGHT" },
          { name: "SPARTA", link: "https://chits-video.s3.amazonaws.com/chitters_debut_SPARTA.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_SPARTA.png", level: "LIGHT" },
          { name: "SPECTACULAR", link: "https://chits-video.s3.amazonaws.com/chitters_debut_SPECTACULAR.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_SPECTACULAR.png", level: "LIGHT" },
          { name: "SPINNYTHING", link: "https://chits-video.s3.amazonaws.com/chitters_debut_SPINNYTHING.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_SPINNYTHING.png", level: "LIGHT" },
          { name: "TAKEN", link: "https://chits-video.s3.amazonaws.com/chitters_debut_TAKEN.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_TAKEN.png", level: "LIGHT" },
          { name: "TBLBROKEN", link: "https://chits-video.s3.amazonaws.com/chitters_debut_TBLBROKEN.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_TBLBROKEN.png", level: "LIGHT" },
          { name: "TISSCRATCH", link: "https://chits-video.s3.amazonaws.com/chitters_debut_TISSCRATCH.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_TISSCRATCH.png", level: "LIGHT" },
          { name: "TOMBSTONE", link: "https://chits-video.s3.amazonaws.com/chitters_debut_TOMBSTONE.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_TOMBSTONE.png", level: "LIGHT" },
          { name: "TWERKGUY", link: "https://chits-video.s3.amazonaws.com/chitters_debut_TWERKGUY.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_TWERKGUY.png", level: "LIGHT" },
          { name: "TWILIGHT", link: "https://chits-video.s3.amazonaws.com/chitters_debut_TWILIGHT.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_TWILIGHT.png", level: "LIGHT" },
          { name: "UNLIMITEDPOWER", link: "https://chits-video.s3.amazonaws.com/chitters_debut_UNLIMITEDPOWER.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_UNLIMITEDPOWER.png", level: "LIGHT" },
          { name: "VROOMVROOM", link: "https://chits-video.s3.amazonaws.com/chitters_debut_VROOMVROOM.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_VROOMVROOM.png", level: "LIGHT" },
          { name: "WAITAMINUTE", link: "https://chits-video.s3.amazonaws.com/chitters_debut_WAITAMINUTE.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_WAITAMINUTE.png", level: "LIGHT" },
          { name: "WANNALIVE", link: "https://chits-video.s3.amazonaws.com/chitters_debut_WANNALIVE.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_WANNALIVE.png", level: "LIGHT" },
          { name: "WHATRTHOSE", link: "https://chits-video.s3.amazonaws.com/chitters_debut_WHATRTHOSE.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_WHATRTHOSE.png", level: "LIGHT" },
          { name: "WHOSEHORSE", link: "https://chits-video.s3.amazonaws.com/chitters_debut_WHOSEHORSE.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_WHOSEHORSE.png", level: "LIGHT" },
          { name: "WHYRUNNING", link: "https://chits-video.s3.amazonaws.com/chitters_debut_WHYRUNNING.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_WHYRUNNING.png", level: "LIGHT" },
          { name: "WHYSPICY", link: "https://chits-video.s3.amazonaws.com/chitters_debut_WHYSPICY.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_WHYSPICY.png", level: "LIGHT" },
          { name: "WORTHYOPPONENT", link: "https://chits-video.s3.amazonaws.com/chitters_debut_WORTHYOPPONENT.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_WORTHYOPPONENT.png", level: "LIGHT" },
          { name: "YEAHBABY", link: "https://chits-video.s3.amazonaws.com/chitters_debut_YEAHBABY.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_YEAHBABY.png", level: "LIGHT" },
          { name: "YOUWOULDNTGETIT", link: "https://chits-video.s3.amazonaws.com/chitters_debut_YOUWOULDNTGETIT.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_YOUWOULDNTGETIT.png", level: "LIGHT" },
        ]
      },
      prompts: {
        create: [
          { level: "LIGHT", prompt: "What I think of Obama" },
          { level: "LIGHT", prompt: "the legacy of the real Mr. Donald Trump" },
          { level: "LIGHT", prompt: "Real shower thoughts" },
          { level: "LIGHT", prompt: "Re: the love of my life" },
          { level: "LIGHT", prompt: "Reaching you regarding your car's extended warranty." },
          { level: "LIGHT", prompt: "The only reason men exist" },
          { level: "LIGHT", prompt: "The only reason women exist" },
          { level: "LIGHT", prompt: "things i used to find under my brothers bed" },
          { level: "LIGHT", prompt: "favorite activities with pre-schoolers" },
          { level: "LIGHT", prompt: "lick here and find happiness" },
          { level: "LIGHT", prompt: "these are cool dude" },
          { level: "LIGHT", prompt: "what I can do with great uncle Lyanne's picture" },
          { level: "LIGHT", prompt: "my morning routine these days" },
          { level: "LIGHT", prompt: "my spirit animal" },
          { level: "LIGHT", prompt: "my right hand vs my left" },
          { level: "LIGHT", prompt: "when women drive" },
          { level: "LIGHT", prompt: "the good old days" },
          { level: "LIGHT", prompt: "culinary delights" },
          { level: "LIGHT", prompt: "somehow I agreed to wake up to this every morning" },
          { level: "LIGHT", prompt: "normalize this" },
          { level: "LIGHT", prompt: "a new trend:" },
          { level: "LIGHT", prompt: "my life on sunday mornings" },
          { level: "LIGHT", prompt: "30 seconds after my dad walks in" },
          { level: "LIGHT", prompt: "everyone make sure to have your camera on" },
          { level: "LIGHT", prompt: "so my daughter tells me you're into legos?" },
          { level: "LIGHT", prompt: "dear delicate desert ficus" },
          { level: "LIGHT", prompt: "I promise you this is me flirting" },
          { level: "LIGHT", prompt: "the lads when I tell them what I do for work" },
          { level: "LIGHT", prompt: "Orville and Wilbur after they came home" },
          { level: "LIGHT", prompt: "my personal solution to the abortion issue" },
          { level: "LIGHT", prompt: "things the mirror hears as I get out of the shower" },
          { level: "LIGHT", prompt: "Elon Musk's reaction to my new invention" },
          { level: "LIGHT", prompt: "my resume for the Suicide Prevention Lifeline" },
        ]
      }
    }
  })
  const onansBedchamber = await prisma.flo.create({
    data: {
      author: "chitters",
      name: "Debut",
      level: 'REGULAR',
      cost: 0,
      chits: {
        create: [
          { name: "ANACONDA", link: "https://chits-video.s3.amazonaws.com/chitters_debut_ANACONDA.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_ANACONDA.png", level: "REGULAR" },
          { name: "BONERALERT", link: "https://chits-video.s3.amazonaws.com/chitters_debut_BONERALERT.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_BONERALERT.png", level: "REGULAR" },
          { name: "BRITNEYBITCH", link: "https://chits-video.s3.amazonaws.com/chitters_debut_BRITNEYBITCH.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_BRITNEYBITCH.png", level: "REGULAR" },
          { name: "CALLAMBULANCE", link: "https://chits-video.s3.amazonaws.com/chitters_debut_CALLAMBULANCE.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_CALLAMBULANCE.png", level: "REGULAR" },
          { name: "DAYTHATIMETYOU", link: "https://chits-video.s3.amazonaws.com/chitters_debut_DAYTHATIMETYOU.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_DAYTHATIMETYOU.png", level: "REGULAR" },
          { name: "DEADPOOL", link: "https://chits-video.s3.amazonaws.com/chitters_debut_DEADPOOL.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_DEADPOOL.png", level: "REGULAR" },
          { name: "DEARDUMBASS", link: "https://chits-video.s3.amazonaws.com/chitters_debut_DEARDUMBASS.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_DEARDUMBASS.png", level: "REGULAR" },
          { name: "DEARSISTER", link: "https://chits-video.s3.amazonaws.com/chitters_debut_DEARSISTER.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_DEARSISTER.png", level: "REGULAR" },
          { name: "DRACARYS", link: "https://chits-video.s3.amazonaws.com/chitters_debut_DRACARYS.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_DRACARYS.png", level: "REGULAR" },
          { name: "ELMO", link: "https://chits-video.s3.amazonaws.com/chitters_debut_ELMO.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_ELMO.png", level: "REGULAR" },
          { name: "ELMOBEAT", link: "https://chits-video.s3.amazonaws.com/chitters_debut_ELMOBEAT.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_ELMOBEAT.png", level: "REGULAR" },
          { name: "FUCKISUPKYLE", link: "https://chits-video.s3.amazonaws.com/chitters_debut_FUCKISUPKYLE.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_FUCKISUPKYLE.png", level: "REGULAR" },
          { name: "HAIRPULL", link: "https://chits-video.s3.amazonaws.com/chitters_debut_HAIRPULL.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_HAIRPULL.png", level: "REGULAR" },
          { name: "HITLER", link: "https://chits-video.s3.amazonaws.com/chitters_debut_HITLER.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_HITLER.png", level: "REGULAR" },
          { name: "HOMELANDER", link: "https://chits-video.s3.amazonaws.com/chitters_debut_HOMELANDER.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_HOMELANDER.png", level: "REGULAR" },
          { name: "JFK", link: "https://chits-video.s3.amazonaws.com/chitters_debut_JFK.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_JFK.png", level: "REGULAR" },
          { name: "JOHNB", link: "https://chits-video.s3.amazonaws.com/chitters_debut_JOHNB.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_JOHNB.png", level: "REGULAR" },
          { name: "SOMETIME", link: "https://chits-video.s3.amazonaws.com/chitters_debut_SOMETIME.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_SOMETIME.png", level: "REGULAR" },
          { name: "WHYAREYOUGAY", link: "https://chits-video.s3.amazonaws.com/chitters_debut_WHYAREYOUGAY.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_WHYAREYOUGAY.png", level: "REGULAR" },
          { name: "WICK", link: "https://chits-video.s3.amazonaws.com/chitters_debut_WICK.mp4", gif: "https://chits-video.s3.amazonaws.com/PREVIEW_chitters_debut_WICK.png", level: "REGULAR" },
        ]
      },
      prompts: {
        create: [
          { level: "REGULAR", prompt: "Me about to invade Poland" },
          { level: "REGULAR", prompt: "what are you doing step-brother?" },
          { level: "REGULAR", prompt: "forgive me daddy for I've been very naughty" },
          { level: "REGULAR", prompt: "live footage of me at the confessional" },
          { level: "REGULAR", prompt: "a candidate for a pulitzer prize" },
          { level: "REGULAR", prompt: "straight guys with boob implants" },
          { level: "REGULAR", prompt: "allah akbar" },
          { level: "REGULAR", prompt: "what no pussy will do to a mf" },
          { level: "REGULAR", prompt: "these violent delights have violent ends" },
          { level: "REGULAR", prompt: "POV: you're Jackie Kennedy" },
          { level: "REGULAR", prompt: "considering the implications of CRT" },
          { level: "REGULAR", prompt: "Biden's diplomatic trip to Jamaica" },
          { level: "REGULAR", prompt: "Bin Laden on September 12th" },
          { level: "REGULAR", prompt: "Nero with marshmellows and a violin" },
          { level: "REGULAR", prompt: "first day as the UN Ambassador to Somalia" },
          { level: "REGULAR", prompt: "finding child molestors and putting them in gladiator matches" },
        ]
      }
    }
  })
}
main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })